root: true
ignorePatterns:
  - node_modules
  - dist
env:
  node: true
  commonjs: true
  es6: true
  mocha: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error